xz for nix auto setup

diff --git a/install/install b/install/install
--- a/install/install
+++ b/install/install
@@ -10,10 +10,15 @@ source_or_dot() {
 }
 
 # nix setup
-
+ # xz is needed for nix doe
 if ! command -v xz &> /dev/null; then
-  echo "install xz if ure on debian run:  sudo apt update && sudo apt -y install xz-utils"
- exit 1;
+  if [ -f "/etc/debian_version" ]; then
+    echo "xz not found. Installing xz-utils on Debian..."
+    sudo apt update && sudo apt -y install xz-utils
+  else
+    echo "xz not found, and you are not on Debian. Exiting."
+    exit 1
+  fi
 fi
 
 sh <(curl -L https://nixos.org/nix/install) --no-daemon
@@ -26,7 +31,14 @@ nix-env -iA \
     nixpkgs.wget \
     nixpkgs.zsh \
     nixpkgs.neovim \
-    nixpkgs.bat 
+    nixpkgs.tmux \
+    nixpkgs.bat \
+    nixpkgs.neofetch \
+    nixpkgs.tree \
+    nixpkgs.htop \
+    nixpkgs.fd \
+    nixpkgs.ripgrep 
+
 
 # dircolors
 curl https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark --output ~/.dircolors
